services:
  db_monitores:
    image: postgres
    env_file:
      - .env.docker
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  monitores:
    build: .
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    env_file:
      - .env.docker
    depends_on:
      - db_monitores

volumes:
  pgdata: